### ISSUE TITLE
signEvent の廃止予定と getSignature への置き換えについて

### ISSUE THREAD

**Issue by awayuki** [nostr-jp/learn-nostr-by-crafting#2]
演習用のコードで使われている、 nostr-tools の signEvent についてです。

https://github.com/nbd-wtf/nostr-tools/blob/bb5acfc19764d1c4e46bba6b1065ef4a25121951/event.ts#L124-L129C2

VS Code で演習問題をやっているときに、
「signEvent が廃止になるため、 getSignature を使いましょう」
という旨のサジェストが出てきました。
（nostr-tools の上記の部分にこの旨の記載があるのも確認しました）

この件について、置き換えまたは補足などあってもいいのかも…？と思い、 Issue を上げた次第です。

ちなみに、演習（1-4まで）を getSignature に置き換えて問題はありませんでした。

すでにご存知でしたらすみません。
よろしくお願いいたします。

**Comment by akiomik** [comment]
`signEvent` は `1.11.1` からdeprecatedになったようです。

https://github.com/nbd-wtf/nostr-tools/blob/1c6f39e4ae9f48ee007be25d3706681ba0c99a8c/event.ts#L123

`package.json` のバージョン指定を `^1.11.1` にして、演習のコードは `getSignature` に書き換えていくのがいいように思いました。

**Comment by awayuki** [comment]
ありがとうございます！
